app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_user_index:
    path: /admin/index
    controller: App\Controller\UserController::index

app_user_new:
    path: /new
    controller: App\Controller\UserController::new

app_user_show:
    path: /{id}
    controller: App\Controller\UserController::show

app_user_edit:
    path: /{id}/edit
    controller: App\Controller\UserController::edit

app_user_delete:
    path: /{id}/delete
    controller: App\Controller\UserController::delete

app_user_profile:
    path: /{id}/profile
    controller: App\Controller\UserController::profile